spring:
  application:
    name: springboot_blockchain_service
  #mvc:
  #  view:
  #    prefix: /views/
  #    suffix: .jsp

  #关闭默认模板引擎
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/thymeleaf/
    suffix: .html
    mode: HTML
    template-resolver-order: 1
    encoding: UTF-8
#  don't need config static-path-pattern and static-locations
#  SpringBoot default-mapping /** to classpath:[/META-INF/resources/, /resources/, /static/, /public/].
#                                and "classpath:/META-INF/resources/", "classpath:/resources/", "classpath:/static/", "classpath:/public/"
#  mvc:
#    static-path-pattern: /resource/**
#  resources:
#    static-locations: classpath:/thymeleaf/static/, classpath:/thymeleaf/static/, classpath:/public/

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/demo?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    hikari: # 使用hikari 连接池
      maximumPoolSize: 15
      minimumIdle: 5
      idleTimeout: 30000
      connectionTimeout: 30000
      maxLifetime: 1800000
      connectionTestQuery: SELECT 1
      poolName: DatebookHikariCP
      autoCommit: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数，默认为 8 。使用负数表示没有限制。
        max-idle: 8 # 默认连接数最大空闲的连接数，默认为 8 。使用负数表示没有限制。
        min-idle: 0 # 默认连接池最小空闲的连接数，默认为 0 。允许设置 0 和 正数。
        max-wait: -1 # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1 ，表示不限制。
server:
  port: 21112
  servlet:
    context-path: /
  ssl:
    enabled: true
    key-store: classpath:key/website_a.jks
    key-password: Admin@1234
    key-store-type: JKS
    key-store-password: Admin@123
    client-auth: NONE
block:
  chain:
    execute: @active@
    consume: 20
    produce: 30
    secure: false
    min-key: 10000000
    max-key: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    api-host: https://blockchain.info/balance
    producer: 2
    consumer: 2
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.yk.demo,com.yk.base