spring:
  application:
    name: springboot_blockchain_service
  #mvc:
  #  view:
  #    prefix: /views/
  #    suffix: .jsp

  #关闭默认模板引擎
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/thymeleaf/
    suffix: .html
    mode: HTML
    template-resolver-order: 1
    encoding: UTF-8
#  don't need config static-path-pattern and static-locations
#  SpringBoot default-mapping /** to classpath:[/META-INF/resources/, /resources/, /static/, /public/].
#                                and "classpath:/META-INF/resources/", "classpath:/resources/", "classpath:/static/", "classpath:/public/"
#  mvc:
#    static-path-pattern: /resource/**
#  resources:
#    static-locations: classpath:/thymeleaf/static/, classpath:/thymeleaf/static/, classpath:/public/
server:
  port: 9023
  servlet:
    context-path: /
  ssl:
    enabled: true
    key-store: classpath:key/website_a.jks
    key-password: Admin@1234
    key-store-type: JKS
    key-store-password: Admin@123
block:
  chain:
    execute: @active@
    consume: 10
    produce: 10
    secure: false
    min-key: 0
    max-key: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF