spring:
  application:
    name: springboot_blockchain_service
  #mvc:
  #  view:
  #    prefix: /views/
  #    suffix: .jsp

  #关闭默认模板引擎
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/thymeleaf/
    suffix: .html
    mode: HTML
    template-resolver-order: 1
    encoding: UTF-8
#  这里不配置 static-path-pattern 和 static-locations
#  SpringBoot默认会映射 /** 到 Defaults to classpath:[/META-INF/resources/, /resources/, /static/, /public/].
#                       以及 "classpath:/META-INF/resources/", "classpath:/resources/", "classpath:/static/", "classpath:/public/"
#  mvc:
#    static-path-pattern: /resource/**
#  resources:
#    static-locations: classpath:/thymeleaf/static/, classpath:/thymeleaf/static/, classpath:/public/
server:
  port: 9023
  servlet:
    context-path: /
  ssl:
    enabled: true
    key-store: classpath:key/website_a.jks
    key-password: Admin@1234
    key-store-type: JKS
    key-store-password: Admin@123