spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1073741824
      max-request-size: 1073741824
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/shiro_demo?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    hikari:
      maximumPoolSize: 15
      minimumIdle: 5
      idleTimeout: 30000
      connectionTimeout: 30000
      maxLifetime: 1800000
      connectionTestQuery: SELECT 1
      poolName: DatebookHikariCP
      autoCommit: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.yk.user.model
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds