cluster.name: es-docker-cluster
node.name: es-single

path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

network.host: 0.0.0.0
http.port: 19200

discovery.type: single-node

xpack.security.enabled: false
