version: '3.9'

services:
  nginx:
    container_name: nginx-container
    image: nginx:latest
    restart: always
    ports:
      - 7999:7999
    volumes:
      # 配置文件nginx.conf是要放在/etc/nginx/目录下的
      # 而nginx.conf中引入的文件(用于独立配置server)，需要放在/etc/nginx/conf.d/目录下
      #- ./config/conf.d:/etc/nginx/conf.d
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/mime.types:/etc/nginx/mime.types:ro
    networks:
      - mynginx
networks:
  mynginx:
    driver: bridge