spring:
  security:
    user:
      name: user1
      password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 1073741824
      max-request-size: 1073741824
trust:
  trust-store: ${catalina.base}/conf/ssl/website.ts
  trust-store-passwd: Admin@123
  verify-uri: /xxxxxx/*
resttemplate:
  proxy:
    host: 127.0.0.1
    port: 60010
upload:
    to-path: upload/video