spring:
  autoconfigure:
    exclude:
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  application:
    name: springboot-service
  security:
    jwt:
      token:
        secret-key: secret-key
        expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/demo?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    hikari:
      maximumPoolSize: 15
      minimumIdle: 5
      idleTimeout: 30000
      connectionTimeout: 30000
      maxLifetime: 1800000
      connectionTestQuery: SELECT 1
      poolName: DatebookHikariCP
      autoCommit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      # dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      format_sql: true
server:
  port: 9098
  servlet:
    context-path: /
    encoding:
      force: true # HttpEncodingAutoConfiguration
  ssl:
    enabled: true
    key-store: classpath:key/website.ks
    key-password: Admin@1234
    key-store-type: JKS
    key-store-password: Admin@123
  error:
    path: /error
secret:
  related:
    excepts: /api/signin;/api/signup